development:
  adapter: postgresql
  database: standup_development
  host: localhost
  min_messages: WARNING

test:
  adapter: postgresql
  database: standup_test
  host: localhost
  min_messages: WARNING
